### ISSUE TITLE
impossible launched 

### ISSUE THREAD

**Issue by fefe64fr** [Dnawrkshp/pc-communicator-ncx#1]
error I think the update of the net cheat x too recent
pc-communicator-ncx/PCCommunicator/Communicator.cs

https://prnt.sc/xbk9cp

**Comment by Dnawrkshp** [comment]
NetCheat X is not functional. Use NetCheat which you can access here https://netcheat.gamehacking.org/ncUpdater/ncUpdateDir.zip

**Comment by fefe64fr** [comment]
Version edit memory vPC ?

**Comment by Dnawrkshp** [comment]
Change the API in the APIs tab to PC
